name: "Fowlie's blog"
description: "Just another blog"

gems:
  - jekyll-paginate
  - jemoji

paginate: 5
url: "http://localhost:4000"
markdown: kramdown
highlighter: rouge

# Outputting
paginate_path: /page:num
